$USER="GEN"
$USER_PASSWORD="1234339827"
$SCHEMA="GEN"
$HOST_ORACLE="localhost"
$PORT="1524"
$SERVICE_NAME="ORCLCDB"

& ".\OracleRabbitMq\load-into.oraclev2.ps1" `
  -USER $USER `
  -USER_PASSWORD $USER_PASSWORD `
  -SCHEMA $SCHEMA `
  -HOST_ORACLE $HOST_ORACLE `
  -PORT $PORT `
  -SERVICE_NAME $SERVICE_NAME