

insert into usuarios (USER_SISTEMA, CEDULA, NOMBRE, ZONA, IMPRESORA, ESTADO, SESIONES, MAIL, IMPRESORA_AUX, TELEFONO_CELULAR, USER_JEFE, EXPEDICION_CEDULA, PASSWORD, TIPO, FECHA_DESACTIVA, FOTO, OFICINA, CARGO, DEPENDENCIA, EXTENSION, FECHA_CREACION)
values ('DRONDON', 1098809038, 'DANIEL GERARDO RONDÓN GARCÍA', 1, null, 'S', 5, 'daniel.rondon@actsis.com', null, 3024218105, 'MVANEGAS', null, null, 'B', null, null, '20', '11115', '144', null, null);

insert into usuarios (USER_SISTEMA, CEDULA, NOMBRE, ZONA, IMPRESORA, ESTADO, SESIONES, MAIL, IMPRESORA_AUX, TELEFONO_CELULAR, USER_JEFE, EXPEDICION_CEDULA, PASSWORD, TIPO, FECHA_DESACTIVA, FOTO, OFICINA, CARGO, DEPENDENCIA, EXTENSION, FECHA_CREACION)
values ('EREYES', 37548698, 'EUDREY REYES', 1, null, 'S', 4, 'eudrey.reyes@actsis.com', null, null, 'CLOPEZ', null, null, 'B', null, null, '20', '11120', '123', null, null);

insert into usuarios (USER_SISTEMA, CEDULA, NOMBRE, ZONA, IMPRESORA, ESTADO, SESIONES, MAIL, IMPRESORA_AUX, TELEFONO_CELULAR, USER_JEFE, EXPEDICION_CEDULA, PASSWORD, TIPO, FECHA_DESACTIVA, FOTO, OFICINA, CARGO, DEPENDENCIA, EXTENSION, FECHA_CREACION)
values ('PSERRANO', 1234339827, 'PABLO EDUARDO SERRANO RINCÓN', 1, null, 'S', 3, 'pablo.serrano@actsis.com', null, 3157363578, 'DRONDON', null, null, 'B', null, null, '20', '11112', '144', null, to_date('27-02-2023 10:23:21', 'dd-mm-yyyy hh24:mi:ss'));

