CREATE TABLE BROKER
  (
    "BROKER_ID" NUMBER(*,0),
    "HOST"      VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "PORT"      NUMBER(*,0) DEFAULT 5672,
    "VHOST"     VARCHAR2(255 BYTE) DEFAULT '/',
    "USERNAME"  VARCHAR2(255 BYTE) DEFAULT 'guest',
    "PASSWORD"  VARCHAR2(255 BYTE) DEFAULT 'guest',
    CONSTRAINT "BROKER_KEY" PRIMARY KEY ("BROKER_ID", "HOST", "PORT") ENABLE
  );
