GRANT SELECT ON V_$PROCESS TO GEN_APP;
GRANT SELECT ON V_$SESSION TO GEN_APP;
GRANT SELECT ON V_$SGASTAT TO GEN_APP;
GRANT SELECT ON V_$QUEUE TO GEN_APP;
GRANT SELECT ON V_$DISPATCHER TO GEN_APP;

GRANT EXECUTE ON DBMS_LOCK TO GEN;
CREATE PUBLIC SYNONYM DBMS_LOCK FOR SYS.DBMS_LOCK;
grant execute ON DBMS_CRYPTO TO GEN
grant execute ON DBMS_PIPE TO GEN