CREATE SMALLFILE TABLESPACE "DATOS_SCP" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\DATOS_SCP.dmp' SIZE 3145728 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "D_GEN" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\D_GEN.dmp' SIZE 5226102784 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "D_SAF" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\D_SAF.dmp' SIZE 524288000 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "D_SAN" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\D_SAN.dmp' SIZE 419430400 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "D_SGI" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\D_SGI.dmp' SIZE 889192448 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "I_GEN" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\I_GEN.dmp' SIZE 1677721600 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "I_SAF" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\I_SAF.dmp' SIZE 1363148800 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "I_SAN" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\I_SAN.dmp' SIZE 230686720 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;
CREATE SMALLFILE TABLESPACE "I_SGI" LOGGING DATAFILE '\opt\oracle\oradata\ORCLCDB\I_SGI.dmp' SIZE 262144000 AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT AUTO ;

GRANT EXECUTE ON DBMS_LOCK TO GEN;
GRANT EXECUTE ON DBMS_PIPE TO GEN;
GRANT EXECUTE ON DBMS_CRYPTO TO GEN;
