-- MySQL Script generated by MySQL Workbench
-- Mon Jan 20 10:28:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgi_azure_db` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sgi_azure_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgi_azure_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgi_azure_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sgi_azure_db` ;

-- -----------------------------------------------------
-- Table `sgi_azure_db`.`requirement_work_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`requirement_work_item` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `requirement_id` INT NOT NULL,
  `work_item_id` INT NOT NULL,
  `customer` VARCHAR(50) NOT NULL,
  `status` ENUM('Enabled', 'Disabled') NOT NULL DEFAULT 'Enabled',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `work_item_id_UNIQUE` (`work_item_id` ASC) VISIBLE,
  UNIQUE INDEX `requirement_id_UNIQUE` (`requirement_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`changelog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`changelog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin` VARCHAR(45) NOT NULL,
  `chage_description` VARCHAR(3000) NOT NULL,
  `change_type` ENUM('created', 'updated', 'deleted') NOT NULL,
  `change_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `requirement_work_item_id` INT NOT NULL,
  PRIMARY KEY (`id`, `requirement_work_item_id`),
  INDEX `fk_changelog_requirement_work_item1_idx` (`requirement_work_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_changelog_requirement_work_item1`
    FOREIGN KEY (`requirement_work_item_id`)
    REFERENCES `sgi_azure_db`.`requirement_work_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`message_processing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`message_processing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` VARCHAR(255) NOT NULL,
  `queue` VARCHAR(45) NOT NULL,
  `requirement_id` INT NULL,
  `work_item_id` INT NULL,
  `status` ENUM('pending', 'processing', 'processed', 'failed') NOT NULL DEFAULT 'pending',
  `error_message` VARCHAR(500) NULL,
  `attempts` INT NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `requirement_work_item_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_message_processing_requirement_work_item_idx` (`requirement_work_item_id` ASC) VISIBLE,
  CONSTRAINT `fk_message_processing_requirement_work_item`
    FOREIGN KEY (`requirement_work_item_id`)
    REFERENCES `sgi_azure_db`.`requirement_work_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `sgi_azure_db` ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
