-- MySQL Script generated by MySQL Workbench
-- Wed Nov 26 10:51:33 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sgi_azure_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sgi_azure_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sgi_azure_db` DEFAULT CHARACTER SET utf8mb3 ;
USE `sgi_azure_db` ;

-- -----------------------------------------------------
-- Table `sgi_azure_db`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `domain` VARCHAR(100) NOT NULL,
  `access_token` VARCHAR(500) NOT NULL,
  `organization` VARCHAR(50) NOT NULL,
  `project` VARCHAR(50) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`requirements_workitems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`requirements_workitems` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `requirement_id` INT NOT NULL,
  `workitem_id` INT NOT NULL,
  `customer` VARCHAR(50) NOT NULL,
  `status` ENUM('E', 'D') NOT NULL DEFAULT 'E',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `work_item_id_UNIQUE` (`workitem_id` ASC) VISIBLE,
  UNIQUE INDEX `requirement_id_UNIQUE` (`requirement_id` ASC) VISIBLE,
  INDEX `fk_requirement_workitems_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_requirement_workitems_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `sgi_azure_db`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 66
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`changelogs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`changelogs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `origin` VARCHAR(45) NOT NULL,
  `chage_description` VARCHAR(2000) NOT NULL,
  `change_type` ENUM('created', 'updated', 'deleted') NOT NULL,
  `change_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `requirements_workitems_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_changelogs_requirements_workitems1_idx` (`requirements_workitems_id` ASC) VISIBLE,
  CONSTRAINT `fk_changelogs_requirements_workitems1`
    FOREIGN KEY (`requirements_workitems_id`)
    REFERENCES `sgi_azure_db`.`requirements_workitems` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 39
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`field_parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`field_parameters` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador numérico del campo creado en base de datos.',
  `code` VARCHAR(50) NOT NULL,
  `code_value` VARCHAR(150) NULL DEFAULT NULL COMMENT 'ruta del campo(opcional y exclusivo de azure)\\\\n',
  `description` VARCHAR(255) NULL DEFAULT NULL COMMENT 'descripción del campo, es opcional.',
  `source_type` ENUM('azure', 'sgi') NOT NULL COMMENT 'Indica si el campo es de azure o del sgi',
  `data_type` ENUM('string', 'int', 'date', 'datetime') NOT NULL DEFAULT 'string' COMMENT 'Tipo de dato que almacena el campo\\\\n',
  `is_active` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'fecha de creación del campo\\\\n',
  `updated_at` TIMESTAMP NULL DEFAULT NULL COMMENT 'fecha de actualización del campo\\\\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 85
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`field_mappings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`field_mappings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `field_source` INT NOT NULL,
  `field_mapped` INT NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customer_field_parameters_field_parameters1_idx` (`field_source` ASC) VISIBLE,
  INDEX `fk_customer_field_parameters_field_parameters2_idx` (`field_mapped` ASC) VISIBLE,
  INDEX `fk_field_mappings_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_customer_field_parameters_field_parameters1`
    FOREIGN KEY (`field_source`)
    REFERENCES `sgi_azure_db`.`field_parameters` (`id`),
  CONSTRAINT `fk_customer_field_parameters_field_parameters2`
    FOREIGN KEY (`field_mapped`)
    REFERENCES `sgi_azure_db`.`field_parameters` (`id`),
  CONSTRAINT `fk_field_mappings_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `sgi_azure_db`.`customers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`field_value_parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`field_value_parameters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value_code` VARCHAR(100) NOT NULL,
  `value_description` VARCHAR(255) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `field_parameters_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_value_parameters_field_parameters_idx` (`field_parameters_id` ASC) VISIBLE,
  CONSTRAINT `fk_field_value_parameters_field_parameters`
    FOREIGN KEY (`field_parameters_id`)
    REFERENCES `sgi_azure_db`.`field_parameters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`field_value_mappings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`field_value_mappings` (
  `id` INT NOT NULL,
  `local_value_id` INT NOT NULL AUTO_INCREMENT,
  `equivalent_value_id` INT NOT NULL,
  `field_parameters_id` INT NOT NULL,
  `target_system` VARCHAR(45) NOT NULL DEFAULT 'azure',
  `customers_id` INT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_field_value_mappings_field_value_parameters1_idx` (`local_value_id` ASC) VISIBLE,
  INDEX `fk_field_value_mappings_field_value_parameters2_idx` (`equivalent_value_id` ASC) VISIBLE,
  INDEX `fk_field_value_mappings_field_parameters1_idx` (`field_parameters_id` ASC) VISIBLE,
  INDEX `fk_field_value_mappings_customers1_idx` (`customers_id` ASC) VISIBLE,
  CONSTRAINT `fk_field_value_mappings_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `sgi_azure_db`.`customers` (`id`),
  CONSTRAINT `fk_field_value_mappings_field_parameters1`
    FOREIGN KEY (`field_parameters_id`)
    REFERENCES `sgi_azure_db`.`field_parameters` (`id`),
  CONSTRAINT `fk_field_value_mappings_field_value_parameters1`
    FOREIGN KEY (`local_value_id`)
    REFERENCES `sgi_azure_db`.`field_value_parameters` (`id`),
  CONSTRAINT `fk_field_value_mappings_field_value_parameters2`
    FOREIGN KEY (`equivalent_value_id`)
    REFERENCES `sgi_azure_db`.`field_value_parameters` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`messages_processing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`messages_processing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message_id` VARCHAR(255) NOT NULL,
  `queue` VARCHAR(45) NOT NULL,
  `requirement_id` INT NULL DEFAULT NULL,
  `work_item_id` INT NULL DEFAULT NULL,
  `status` ENUM('pending', 'processing', 'processed', 'failed') NOT NULL DEFAULT 'pending',
  `error_message` VARCHAR(500) NULL DEFAULT NULL,
  `attempts` INT NOT NULL DEFAULT '0',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `requirements_workitems_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_messages_processing_requirements_workitems1_idx` (`requirements_workitems_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_processing_requirements_workitems1`
    FOREIGN KEY (`requirements_workitems_id`)
    REFERENCES `sgi_azure_db`.`requirements_workitems` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`work_artifacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`work_artifacts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `type` ENUM('requirement', 'workitem') NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `sgi_azure_db`.`work_artifacts_mappings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sgi_azure_db`.`work_artifacts_mappings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `type` ENUM('requirement', 'workitem') NOT NULL,
  `enabled` TINYINT NOT NULL DEFAULT '1',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT NULL,
  `customers_id` INT NOT NULL,
  `requirement_artifact_id` INT NOT NULL,
  `workitem_artifact_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_work_artifacts_mappings_customers1_idx` (`customers_id` ASC) VISIBLE,
  INDEX `fk_work_artifacts_mappings_work_artifacts1_idx` (`requirement_artifact_id` ASC) VISIBLE,
  INDEX `fk_work_artifacts_mappings_work_artifacts2_idx` (`workitem_artifact_id` ASC) VISIBLE,
  CONSTRAINT `fk_work_artifacts_mappings_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `sgi_azure_db`.`customers` (`id`),
  CONSTRAINT `fk_work_artifacts_mappings_work_artifacts1`
    FOREIGN KEY (`requirement_artifact_id`)
    REFERENCES `sgi_azure_db`.`work_artifacts` (`id`),
  CONSTRAINT `fk_work_artifacts_mappings_work_artifacts2`
    FOREIGN KEY (`workitem_artifact_id`)
    REFERENCES `sgi_azure_db`.`work_artifacts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
